from PyQt5 import QtCore, QtGui, QtWidgets



class HelpWidget(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(HelpWidget, self).__init__(parent)

        # help_page
        self.setObjectName("help_page")

        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_9.setObjectName("verticalLayout_9")

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")

        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)

        self.pushButton_2 = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(130, 40))
        self.pushButton_2.setMaximumSize(QtCore.QSize(130, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)

        self.pushButton_3 = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(130, 40))
        self.pushButton_3.setMaximumSize(QtCore.QSize(130, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)

        self.pushButton_4 = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(130, 40))
        self.pushButton_4.setMaximumSize(QtCore.QSize(130, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)

        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)

        self.verticalLayout_9.addLayout(self.horizontalLayout)

        self.help_windows = QtWidgets.QStackedWidget(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help_windows.sizePolicy().hasHeightForWidth())
        self.help_windows.setSizePolicy(sizePolicy)
        self.help_windows.setMinimumSize(QtCore.QSize(1375, 790))
        self.help_windows.setMaximumSize(QtCore.QSize(1375, 790))
        self.help_windows.setObjectName("help_windows")

        self.image_capture_help = QtWidgets.QWidget()
        self.image_capture_help.setObjectName("image_capture_help")

        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.image_capture_help)
        self.verticalLayout_8.setObjectName("verticalLayout_8")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.camera_feed_label_2 = QtWidgets.QLabel(self.image_capture_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_feed_label_2.sizePolicy().hasHeightForWidth())
        self.camera_feed_label_2.setSizePolicy(sizePolicy)
        self.camera_feed_label_2.setMinimumSize(QtCore.QSize(330, 50))
        self.camera_feed_label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.camera_feed_label_2.setObjectName("camera_feed_label_2")
        self.verticalLayout_3.addWidget(self.camera_feed_label_2)

        self.label = QtWidgets.QLabel(self.image_capture_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(960, 30))
        self.label.setMaximumSize(QtCore.QSize(960, 30))
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)

        self.label_2 = QtWidgets.QLabel(self.image_capture_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(820, 40))
        self.label_2.setMaximumSize(QtCore.QSize(820, 40))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)

        self.label_4 = QtWidgets.QLabel(self.image_capture_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(1120, 40))
        self.label_4.setMaximumSize(QtCore.QSize(1120, 40))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)

        spacerItem8 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem8)

        self.camera_feed_label_3 = QtWidgets.QLabel(self.image_capture_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_feed_label_3.sizePolicy().hasHeightForWidth())
        self.camera_feed_label_3.setSizePolicy(sizePolicy)
        self.camera_feed_label_3.setMinimumSize(QtCore.QSize(330, 50))
        self.camera_feed_label_3.setMaximumSize(QtCore.QSize(330, 50))
        self.camera_feed_label_3.setObjectName("camera_feed_label_3")
        self.verticalLayout_3.addWidget(self.camera_feed_label_3)

        self.label_6 = QtWidgets.QLabel(self.image_capture_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(690, 40))
        self.label_6.setMaximumSize(QtCore.QSize(690, 40))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)

        self.label_7 = QtWidgets.QLabel(self.image_capture_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(730, 40))
        self.label_7.setMaximumSize(QtCore.QSize(730, 40))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)

        self.label_3 = QtWidgets.QLabel(self.image_capture_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(970, 40))
        self.label_3.setMaximumSize(QtCore.QSize(970, 40))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)

        self.verticalLayout_8.addLayout(self.verticalLayout_3)
        self.help_windows.addWidget(self.image_capture_help)

        self.detection_help = QtWidgets.QWidget()
        self.detection_help.setObjectName("detection_help")

        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.detection_help)
        self.verticalLayout_7.setObjectName("verticalLayout_7")

        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.camera_feed_label_4 = QtWidgets.QLabel(self.detection_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_feed_label_4.sizePolicy().hasHeightForWidth())
        self.camera_feed_label_4.setSizePolicy(sizePolicy)
        self.camera_feed_label_4.setMinimumSize(QtCore.QSize(340, 50))
        self.camera_feed_label_4.setMaximumSize(QtCore.QSize(340, 50))
        self.camera_feed_label_4.setObjectName("camera_feed_label_4")
        self.verticalLayout_4.addWidget(self.camera_feed_label_4)

        self.label_5 = QtWidgets.QLabel(self.detection_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(800, 30))
        self.label_5.setMaximumSize(QtCore.QSize(800, 30))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)

        self.label_8 = QtWidgets.QLabel(self.detection_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(1100, 40))
        self.label_8.setMaximumSize(QtCore.QSize(1100, 40))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)

        self.label_9 = QtWidgets.QLabel(self.detection_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(750, 40))
        self.label_9.setMaximumSize(QtCore.QSize(750, 40))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)

        self.label_13 = QtWidgets.QLabel(self.detection_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(800, 40))
        self.label_13.setMaximumSize(QtCore.QSize(800, 40))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)

        spacerItem9 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem9)

        self.camera_feed_label_5 = QtWidgets.QLabel(self.detection_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_feed_label_5.sizePolicy().hasHeightForWidth())
        self.camera_feed_label_5.setSizePolicy(sizePolicy)
        self.camera_feed_label_5.setMinimumSize(QtCore.QSize(250, 50))
        self.camera_feed_label_5.setMaximumSize(QtCore.QSize(250, 50))
        self.camera_feed_label_5.setObjectName("camera_feed_label_5")
        self.verticalLayout_4.addWidget(self.camera_feed_label_5)

        self.label_10 = QtWidgets.QLabel(self.detection_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(820, 40))
        self.label_10.setMaximumSize(QtCore.QSize(820, 40))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)

        self.label_11 = QtWidgets.QLabel(self.detection_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(900, 40))
        self.label_11.setMaximumSize(QtCore.QSize(900, 40))
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)

        self.label_12 = QtWidgets.QLabel(self.detection_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(920, 40))
        self.label_12.setMaximumSize(QtCore.QSize(920, 40))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)

        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.help_windows.addWidget(self.detection_help)

        self.gen_report_help = QtWidgets.QWidget()
        self.gen_report_help.setObjectName("gen_report_help")

        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gen_report_help)
        self.verticalLayout_6.setObjectName("verticalLayout_6")

        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")

        self.camera_feed_label_6 = QtWidgets.QLabel(self.gen_report_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_feed_label_6.sizePolicy().hasHeightForWidth())
        self.camera_feed_label_6.setSizePolicy(sizePolicy)
        self.camera_feed_label_6.setMinimumSize(QtCore.QSize(200, 50))
        self.camera_feed_label_6.setMaximumSize(QtCore.QSize(200, 50))
        self.camera_feed_label_6.setObjectName("camera_feed_label_6")
        self.verticalLayout_5.addWidget(self.camera_feed_label_6)

        self.label_14 = QtWidgets.QLabel(self.gen_report_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(750, 30))
        self.label_14.setMaximumSize(QtCore.QSize(750, 30))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)

        self.label_15 = QtWidgets.QLabel(self.gen_report_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(1000, 40))
        self.label_15.setMaximumSize(QtCore.QSize(1000, 40))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)

        self.label_16 = QtWidgets.QLabel(self.gen_report_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(950, 40))
        self.label_16.setMaximumSize(QtCore.QSize(950, 40))
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)

        self.label_17 = QtWidgets.QLabel(self.gen_report_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(500, 40))
        self.label_17.setMaximumSize(QtCore.QSize(500, 40))
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)

        spacerItem10 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem10)

        self.camera_feed_label_7 = QtWidgets.QLabel(self.gen_report_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_feed_label_7.sizePolicy().hasHeightForWidth())
        self.camera_feed_label_7.setSizePolicy(sizePolicy)
        self.camera_feed_label_7.setMinimumSize(QtCore.QSize(200, 50))
        self.camera_feed_label_7.setMaximumSize(QtCore.QSize(200, 50))
        self.camera_feed_label_7.setObjectName("camera_feed_label_7")
        self.verticalLayout_5.addWidget(self.camera_feed_label_7)

        self.label_18 = QtWidgets.QLabel(self.gen_report_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(700, 40))
        self.label_18.setMaximumSize(QtCore.QSize(700, 40))
        self.label_18.setObjectName("label_18")
        self.verticalLayout_5.addWidget(self.label_18)

        self.label_19 = QtWidgets.QLabel(self.gen_report_help)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(500, 40))
        self.label_19.setMaximumSize(QtCore.QSize(500, 40))
        self.label_19.setObjectName("label_19")
        self.verticalLayout_5.addWidget(self.label_19)

        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.help_windows.addWidget(self.gen_report_help)
        self.verticalLayout_9.addWidget(self.help_windows)

        # button functionality
        self.pushButton_2.clicked.connect(lambda: self.help_windows.setCurrentWidget(self.image_capture_help))
        self.pushButton_3.clicked.connect(lambda: self.help_windows.setCurrentWidget(self.detection_help))
        self.pushButton_4.clicked.connect(lambda: self.help_windows.setCurrentWidget(self.gen_report_help))


        # translate help_page
        self.translatePage()

    def translatePage(self):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_2.setText(_translate("MainWindow", "Image Capture"))
        self.pushButton_3.setText(_translate("MainWindow", "Detection"))
        self.pushButton_4.setText(_translate("MainWindow", "Generate Report"))

        self.camera_feed_label_2.setText(_translate("MainWindow", "o  Camera Live Feed"))
        self.label.setText(_translate("MainWindow", "1. Take pictures of the current motherboard under test. If your computer does not have a camera device, this feature will be disabled by default."))
        self.label_2.setText(_translate("MainWindow", "NOTE: To use a new camera device, connect it to the computer and restart the program so that the device can be identified."))
        self.label_4.setText(_translate("MainWindow", "2. Pictures you have taken can be found under the \'Motherboard Images/Defect Images\' folder by default. Choose \'Save As\' to customize the picture name and location."))
        self.camera_feed_label_3.setText(_translate("MainWindow", "o Select Images For Detection"))
        self.label_6.setText(_translate("MainWindow", "1. Select images of the motherboard (including the motherboard QR code sticker) and Barcode sticker."))
        self.label_7.setText(_translate("MainWindow", "NOTE: To proceed to the Detection page, you must select files with an image file extension (.png, .jpg, .jpeg)."))
        self.label_3.setText(_translate("MainWindow", "2. Please ensure that the QR code and Barcode stickers are not rotated more than 90-degrees clockwise or counterclockwise for proper detection."))
        self.camera_feed_label_4.setText(_translate("MainWindow", "o QR Code/Barcode Recognition"))
        self.label_5.setText(_translate("MainWindow", "1. To identify the motherboard model, run the QR Code and Barcode recognition buttons using the respective buttons."))
        self.label_8.setText(_translate("MainWindow", "NOTE: If recognition fails, check that the QR Code and Barcode stickers are clearly visible on the chosen images. You can reselect images in the Image Capture page."))
        self.label_9.setText(_translate("MainWindow", "2. If the QR Code/Barcode recognition is successful, the motherboard PPID will be displayed on the screen."))
        self.label_13.setText(_translate("MainWindow", "NOTE: If the motherboard PPID is already known, you can manually input the PPID to skip the recognition process."))
        self.camera_feed_label_5.setText(_translate("MainWindow", "o Image Comparison"))
        self.label_10.setText(_translate("MainWindow", "1. Click on the \'Run Comparison\' button to compare the current motherboard model with a \'golden\' sample of the model."))
        self.label_11.setText(_translate("MainWindow", "NOTE: Image comparison cannot be performed until a valid PPID is found based on the motherboard\'s QR Code and Barcode sticker."))
        self.label_12.setText(_translate("MainWindow", "2. When the comparison is complete, images of the \'golden\' motherboard sample and comparison result will be displayed on the screen."))
        self.camera_feed_label_6.setText(_translate("MainWindow", "o Generate Report"))
        self.label_14.setText(_translate("MainWindow", "1. Before generating a report, input your information using the boxes in the \'General Information\' section."))
        self.label_15.setText(_translate("MainWindow", "NOTE: Click the \'Update\' button to update the information of you and your machine for the program. This information will be displayed on the screen."))
        self.label_16.setText(_translate("MainWindow", "2. Generate the report. The report will include your general information and the results of the most recent motherboard image comparison."))
        self.label_17.setText(_translate("MainWindow", "NOTE: Choose \'Save As\' to customize the report name and location."))
        self.camera_feed_label_7.setText(_translate("MainWindow", "o Restart Program"))
        self.label_18.setText(_translate("MainWindow", "1. Restarting the program will return you to the Image Capture page and reset the chosen image files."))
        self.label_19.setText(_translate("MainWindow", "NOTE: Restarting the program will not reset your general information."))
